### ISSUE TITLE
processors/github_metadata: gather pushed_at instead of updated_at

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/hecat#53]
`updated_at` seems to reflect the date of last change (description, issues, comments, PRs, ...) to a repository, but we want the date of last commit to the default branch.

Use `pushed_at`? (the meaning of API responses fields is not clearly documented).

Followup to https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3183

Related https://github.com/nodiscc/hecat/issues/48, the same behaviour is needed for Gitlab projects.

/cc @KieranRobson

**Comment by KieranRobson** [comment]
Since `updated at` will take issues made and prs created as updated, `pushed_at` may be the better choice since the last commit, however the two that marked as `2016` within https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3183 actually showed as `2019` within the commit check script. It was only after I checked for myself on the repo did I see the last commit date as 2016

**Comment by nodiscc** [comment]
Change made in https://github.com/nodiscc/hecat/pull/55, by consequence the number of warnings about stale projects has increased by many: https://github.com/nodiscc/hecat/runs/7672422797?check_suite_focus=true#step:3:867

**Comment by nodiscc** [comment]
https://api.github.com/repos/ZizzyDizzyMC/linx-server: `pushed_at | "2022-06-27T14:43:35Z"` but the latest commit https://github.com/ZizzyDizzyMC/linx-server/commits/master is from 2021-12-24...

There is no mention of 2021-12-24 anywhere in the API response.

**Comment by nodiscc** [comment]
Ref. https://github.com/awesome-selfhosted/awesome-selfhosted/issues/3499

/cc @sarmong
